### ISSUE TITLE
卡常技巧 | 梦安咖啡馆

### ISSUE THREAD

**Issue by Hookan** [Hookan/BlogComment#17]
https://blog.hookan.top/2018/11/07/ka_chang/

**Comment by StudyingFather** [comment]
其实在NOIP级别的比赛中，卡常数的意义似乎不算太大吧...

而且不少底层优化其实编译器都会帮我们优化好，所以即使加了似乎也没有明显效果？

**Comment by Hookan** [comment]
@StudyingFather NOIP当中使用常数优化还是有意义的（毕竟CCF老爷机），而且NOIP当中是没有编译优化的，不要幻想底层编译器帮你优化233

至于效果明不明显我已经在博客当中说明

**Comment by qedens** [comment]
感觉inline优化的效果是挺玄学的……
但是register在数据规模大的循环里测了下效果挺明显的哇QAQ

**Comment by HeartyYF** [comment]
inline还是比较依靠编译器啦，比如某巨硬编译器能展开递归内联函数。。玄学2333而且现在编译器会自动判断一个函数该不该内联，关键字声明inline并不是强制的，而是建议的，从c++17开始变量也能用inline关键词声明了，含义不再是“内联”而是用于说明这个函数或变量出现过不止一次而所有的解释都相同
在c++17前register用于建议编译器将变量存储在寄存器里，但这个关键字在c++17里被废了（deprecated），也有人提出了删掉这个关键字，目前实现还是取决于编译器。。

**Comment by ghost** [comment]
1.位运算对正负优化没啥大的影响
2.fread对大数据效果较好，平常使用的确会负优化
3.结构体那个我觉得是评测机波峰卡常
4.inline现在的NOI貌似使用的不是C++11所以可能会不让用，但是noip貌似可以
5.洛谷评测机很玄学，建议上duckoj测一下
