### ISSUE TITLE
再见了，信息学奥赛 | 梦安咖啡馆

### ISSUE THREAD

**Issue by Hookan** [Hookan/BlogComment#18]
https://blog.hookan.top/2019/02/13/goodbyeoi/

**Comment by qedens** [comment]
不论您是退役还是继续，感谢您在oi上给过我的帮助。
作为朋友表示还是很挽留把，能说的也就这么多了。嗯，以及……祝您高考顺利，考上理想大学。

**Comment by tdiant** [comment]
祝你顺利！永远支持你！

**Comment by npofsi** [comment]
虽然只聊过一次天，但是同为 oier 也祝愿你能顺利，前程未知，但努力没有错，加油 hookan！

**Comment by lyzqs** [comment]
同为一名OIer，我无法想象退役的痛苦
嗯，祝你顺利吧

**Comment by StudyingFather** [comment]
hookan加油鸭！

**Comment by yushijinhun** [comment]
条条大路通罗马。漫漫人生路，何必执着于一条？

**Comment by DLumina** [comment]
嗯...不知道该说什么，祝你顺利！

**Comment by MZMH** [comment]
加油

**Comment by 2323122** [comment]
再见啦....祝你顺利！
Hookan一定会成功的

**Comment by ghost** [comment]
QWQ祝你顺利

**Comment by ForkKILLET** [comment]
初一蒟蒻（好吧快要初二了）表示 ORZ + 加油！！

**Comment by MZMH** [comment]
恩一起加油




------------------ 原始邮件 ------------------
发件人: "ForkΨKillet"<notifications@github.com>; 
发送时间: 2019年7月8日(星期一) 下午5:46
收件人: "Hookan/BlogComment"<BlogComment@noreply.github.com>; 
抄送: "我小猪&#x1F437;佩奇&乔治带你飞"<1392839887@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Hookan/BlogComment] 再见了，信息学奥赛 | 梦安咖啡馆 (#18)




初一蒟蒻（好吧快要初二了）表示 ORZ + 加油！！

**Comment by ForkKILLET** [comment]
:smiley:

**Comment by ghost** [comment]
hookan&&I AK 高考

**Comment by Catalan1906** [comment]
hookan AK 高考
