### ISSUE TITLE
新博客搭建完成！

### ISSUE THREAD

**Issue by Hookan** [Hookan/BlogComment#19]
https://blog.hookan.top/xin-bo-ke-da-jian-wan-cheng/

**Comment by Hookan** [comment]
评论测试qwq

**Comment by RancherJie** [comment]
模组开发教程还更新吗

**Comment by Hookan** [comment]
> 模组开发教程还更新吗

不更新了qwq

**Comment by huangzong1998** [comment]
回头翻看MOD教程，发现博客重新装修了 :)

**Comment by Hookan** [comment]
> @huangzong1998
> 回头翻看MOD教程，发现博客重新装修了 :)

其实mod教程的数据并没有被删除，如果你还想看的话可以从[这里](https://github.com/Hookan/hookan.github.io)clone下来，在本地看

**Comment by WRtux** [comment]
嘛，路过打卡
